### ISSUE TITLE
Query with sentinel2 and LEVEL3A don't work

### ISSUE THREAD

**Issue by pobsteta** [norival/theiaR#4]
Hi,

This query don't work : 
myquery <- list(collection  = "SENTINEL2",
                tile        = "T31UDQ",
                level     = "LEVEL3A",
                start.date  = "2018-07-10",
                end.date    = "2018-07-14")
mycollection$status must return 
1 SENTINEL2X_20180712-225116-772_L3A_T31UDQ_D.zip

and not : tile exists checked correct extracted
1 SENTINEL2A_20180713-110521-625_L2A_T31UDQ_D  FALSE   FALSE   FALSE     FALSE
2 SENTINEL2A_20180710-105618-414_L2A_T31UDQ_D  FALSE   FALSE   FALSE     FALSE

**Comment by norival** [comment]
Hi ! Thanks for reporting an issue :)

Can you give me more details, please?

I checked this query and I get : 

```
> mycollection$status
                                         tile exists checked correct extracted
1 SENTINEL2X_20180712-225116-772_L3A_T31UDQ_D  FALSE   FALSE   FALSE     FALSE
```
which is the expected output.

You must then run `mycollection$download('path/to/auth.file')` to download the tile.

**Comment by pobsteta** [comment]
It is an error from me ! I have change level to "LEVEL2A" instead "LEVEL3A". You can remove this issue.
Thanks for your response.
