### ISSUE TITLE
New VENUS collection

### ISSUE THREAD

**Issue by Rapsodia86** [norival/theiaR#9]
There are two collections of the Venus dataset (https://theia.cnes.fr).
collection=VENUSVM05 & collection=VENUS (of VM1)
Any chance that can be added? 

Thanks!

**Comment by norival** [comment]
Hi!

I added the VENUSVM05 collection as possible value, this should work. You can use it with the dev version of the package until it is published to CRAN:

```r
devtools::install_github('norival/theiaR)
```

**Comment by Rapsodia86** [comment]
Hm...I am getting: "Error: No tiles matching search criteria"
Using either VENUS or VENUSVM05

**Comment by norival** [comment]
What query did you make?

I just tested with these terms, and I get 256 tiles:

```r
query <- list(
  collection = "VENUSVM05",
  start.date = "2023-01-01",
  end.date = "2023-02-03"
)

(collection <- TheiaCollection$new(query = query, dir.path = ".", check = TRUE))
```

**Comment by Rapsodia86** [comment]
Ok, maybe a dummy question, but how I can search thru locations? 
I tried:
> myquery <- list(collection = "VENUS",platform = "VENUS",level="LEVEL2A",
                 town = "KONZA",start.date = "2019-01-01", end.date   = "2019-07-06")
> mycollection <- TheiaCollection$new(query = myquery, dir.path = ".", check = TRUE)
Error: No tiles matching search criteria

And
> myquery <- list(collection = "VENUS",platform = "VENUS",level="LEVEL2A",
                 tile = "KONZA",start.date = "2019-01-01", end.date   = "2019-07-06")
 
> mycollection <- TheiaCollection$new(query = myquery, dir.path = ".", check = TRUE)
Error: 'Tile' is not available for VENUS collection

**Comment by norival** [comment]
You would specify it with `town`, like you did :)

But I guess there is no tile for this time period, the results are the same when searching from the web interface:

[https://theia.cnes.fr/atdistrib/rocket/#/search?page=1&q=KONZA&startDate=2019-01-01&completionDate=2019-07-06](https://theia.cnes.fr/atdistrib/rocket/#/search?page=1&q=KONZA&startDate=2019-01-01&completionDate=2019-07-06)

**Comment by Rapsodia86** [comment]
There is a bunch of data, otherwise I would not search for them;) 
See: https://theia.cnes.fr/atdistrib/rocket/#/search?page=1&platform=VENUS&productType=REFLECTANCE&processingLevel=LEVEL2A&sensorMode=&startDate=2019-01-01&completionDate=2019-07-06&location=KONZA

**Comment by norival** [comment]
Ok, my bad! You must use the `tile` option for this. I just pushed a fix. If you install from github again, it should work. Please let me know if it is ok :)

**Comment by Rapsodia86** [comment]
Yeah! Now works! Thank you! 
And for VM5 as well:)

**Comment by norival** [comment]
Ok, nice! Thanks for your feedback :)
I will update the CRAN release soon.

**Comment by Rapsodia86** [comment]
Although it is a separate thing, as an enhancement probably. I noticed in your code that you use raster package. Now, to move forward, terra package replaces the raster one (https://github.com/rspatial/terra).
